endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client: 
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  server: 
    response-cache-update-interval-ms: 5000
    
ribbon: 
  serverListRefreshInterval: 1000

eventBus:
  broker: redis
  redisHost: localhost
  redisPort: 6379
  redisTopic: csrt-event-bus
  
#spring:
#  rabbitmq:
#    host: ip-172-31-30-255.us-west-2.compute.internal
#    port: 9001

hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 30
server.tomcat.max-threads: 300
