endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5

spring:
  rabbitmq:
    host: 172.31.30.253
    port: 8766
