endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5

spring:
  rabbitmq:
    host: 172.31.7.158
    port: 8760
