endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 30
  client: 
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
  server: 
    response-cache-update-interval-ms: 5000

ribbon: 
  serverListRefreshInterval: 1000

spring:
  rabbitmq:
    host: 172.31.30.253
    port: 8766
